food_site/accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import RegisterView, LoginView, ResetPasswordView, ResetPasswordConfirmView, ProfileView
from django.contrib.auth.views import LogoutView

app_name = 'accounts'
urlpatterns = [
    path('register/', RegisterView.as_view(),name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('log-out/', LogoutView.as_view(), name='log-out'),
    path('reset-password/', ResetPasswordView.as_view(), name='reset-password'),
    path('password-reset-confirm/<str:uidb64>/<str:token>/', ResetPasswordConfirmView.as_view(), name = 'password-reset-confirm'),
    path('user-profile/<int:pk>', ProfileView.as_view(), name='user-profile'),
]

food_site/food_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('stories.urls', namespace='stories')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('api/v1/', include('stories.api.urls', namespace='stories-api')),
]

food_site/stories/urls.py
from django.urls import path

from .views import RecipeListView, ContactView, AboutView, CreateStoryView, IndexView

app_name = "stories"

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('recipes/', RecipeListView.as_view(), name='recipe'),
    path('contacts/', ContactView.as_view(), name='contact'),
    path('create-story/', CreateStoryView.as_view(), name='create_story'),
    path('about/', AboutView.as_view(), name='about'),
    

]

food_site/accounts/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    GENDER_CHOICES = (
        ("Male", ("Male")),
        ("Female", ("Female"))
    )
    bio = models.TextField(max_length=1000, blank=True)
    profile_img = models.ImageField(upload_to='images')
    gender = models.CharField(choices=GENDER_CHOICES, max_length=6)
    email = models.EmailField(max_length=250)

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'
    

food_site/accounts/forms.py
from django import forms 
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordResetForm, SetPasswordForm
from .models import User

class RegisterForm(UserCreationForm):
    password1 = forms.CharField(
        widget = forms.PasswordInput(
            attrs={
                'placeholder' : 'Password',
                'class' : 'form-control',
            }))

    password2 = forms.CharField(
        widget = forms.PasswordInput(
            attrs={
                'placeholder' : 'Confirm password',
                'class' : 'form-control',
             }))

    class Meta:
        model = User
        fields = ('first_name','last_name','username','email','password1','password2')

        widgets = {
            'first_name': forms.TextInput(attrs={'id':'first_name','placeholder':'First name', 'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'id':'last_name','placeholder':'Last name', 'class': 'form-control'}),
            'username': forms.TextInput(attrs={'id':'username','placeholder':'Username', 'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'id':'email','placeholder':'Email', 'class': 'form-control'}),
        }



class LoginForm(AuthenticationForm):
    password = forms.CharField(
        widget = forms.PasswordInput(
            attrs={
                'placeholder' : 'Password',
                'class' : 'form-control',
            }))

    username = forms.CharField(
        widget = forms.TextInput(
            attrs={
                'id': 'username',
                'placeholder': 'Your Username',
                'class': 'form-control'
            }))

    class Meta:
        model = User
        fields = ['username', 'password']




class ResetItDown(PasswordResetForm):
    email = forms.EmailField(
        widget = forms.EmailInput(attrs={
            'placeholder': 'Your Email',
            'class': 'form-control',
        })
    )

class PasswordResetConfirmForm(SetPasswordForm):
    new_password1 = forms.CharField(
        widget = forms.PasswordInput(
            attrs={
                'placeholder' : 'New password',
                'class' : 'form-control',
             }))

    new_password2 = forms.CharField(
        widget = forms.PasswordInput(
            attrs={
                'placeholder' : 'Re-enter new password',
                'class' : 'form-control',
             }))

    class Meta:
        fields = ("new_password1", 'new_password2', )

food_site/accounts/views.py
from django.shortcuts import render
from accounts.models import User
from django.views.generic import ListView, CreateView, DetailView, TemplateView
from accounts.forms import RegisterForm, LoginForm, ResetItDown, PasswordResetConfirmForm
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView, PasswordResetView, PasswordResetConfirmView


class RegisterView(CreateView):
    form_class = RegisterForm
    template_name = 'register.html'
    success_url = reverse_lazy('accounts:login')


class LoginView(LoginView):
    form_class = LoginForm
    template_name = 'login.html'


class ResetPasswordView(PasswordResetView):
    form_class = ResetItDown
    template_name = 'forget_password.html'
    success_url = reverse_lazy('accounts:login')
    email_template_name = 'password_reset_email.html'


class ResetPasswordConfirmView(PasswordResetConfirmView):
    form_class = PasswordResetConfirmForm
    template_name= "reset_password.html" 
    success_url = reverse_lazy('accounts:login')
    

class ProfileView(DetailView):
    model = User
    template_name = 'user-profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

food_site/accounts/templates/change_password.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<section class="ftco-section contact-section register">
        <div class="container">
            <div class="row block-9 justify-content-center">
                <div class="col-md-6 order-md-last d-flex">
                    <form action="#" class="bg-light p-5 contact-form">
                        <div class="form-group">
                            <h4 class="reset center">Change your password</h4>
                            <h6 class="center">Please choose a new password to finish signing in.</h6>
                        </div>
                        <div class="form-group">
                            <input type="email" class="form-control" placeholder="New password">
                        </div>
                        <div class="form-group">
                            <input type="email" class="form-control" placeholder="Re-enter new password">
                        </div>
                        <div class="form-group center">
                            <input type="submit" value="Change password" class="btn btn-primary py-3 px-5">
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </section>


<!-- loader -->
<div id="ftco-loader" class="show fullscreen">
    <svg class="circular" width="48px" height="48px">
        <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
        <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                stroke="#F96D00"/>
    </svg>
</div>


{% endblock content %}


    {% block js %}
    {% endblock %}

food_site/accounts/templates/forget_password.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

 <section class="ftco-section contact-section register">
        <div class="container">
            <div class="row block-9 justify-content-center">
                <div class="col-md-6 order-md-last d-flex">
                    <form action="" class="bg-light p-5 contact-form" method="POST">
                        <div class="form-group">
                            <h4 class="reset center">Reset password</h4>
                            <h6 class="center">Please enter your email address to request a password reset.</h6>
                        </div>
                        {% csrf_token %}
                        {{form.non_field_error}}
                        <div class="form-group">
                            {{form.email}}
                            {{form.email.errors}}
                        </div>
                        <div class="form-group center">
                            <input type="submit" value="Reset password" class="btn btn-primary py-3 px-5">
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </section>


<!-- loader -->
<div id="ftco-loader" class="show fullscreen">
    <svg class="circular" width="48px" height="48px">
        <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
        <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                stroke="#F96D00"/>
    </svg>
</div>


{% endblock content %}


    {% block js %}
    {% endblock %}

food_site/accounts/templates/login.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<section class="ftco-section contact-section register">
        <div class="container">
            <div class="row block-9 justify-content-center">
                <div class="col-md-6 order-md-last d-flex">
                    <form action="" class="bg-light p-5 contact-form" method="POST" enctype="multipart/form-data">
                        <a class="navbar-brand center" href="#">Stories<span>.</span></a>
                        {% csrf_token %}
                        {{form.non_field_error}}
                        <div class="form-group">
                            {{form.username}}
                            {{form.username.errors}}
                        </div>
                        <div class="form-group">
                            {{form.password}}
                            {{form.password.errors}}
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Login" class="btn btn-primary py-3 px-5">
                            <a href="{% url 'accounts:reset-password' %}" class="forgot-password">Forgot password?</a>
                        </div>
                        <div class="form-group">
                            <a href="{% url 'accounts:register' %}" class="">Don't have an account? Sign up</a>
                        </div>
			<div class="form-group center">
                            <a href="#" class="social"><i class="fa fa-facebook social-login fb-color"></i></a>
                            <a href="#" class="social"><i class="fa fa-google-plus social-login google-color"></i></a>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </section>


<!-- loader -->
<div id="ftco-loader" class="show fullscreen">
    <svg class="circular" width="48px" height="48px">
        <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
        <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                stroke="#F96D00"/>
    </svg>
</div>


{% endblock content %}


    {% block js %}
    {% endblock %}

food_site/accounts/templates/password_reset_email.html
{% load i18n %}
{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
Sifrenizi deyismek ucun bura tiklayin!
{{ protocol }}://{{ domain }}{% url 'accounts:password-reset-confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

food_site/accounts/templates/register.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<section class="ftco-section contact-section register">
        <div class="container">
            <div class="row block-9 justify-content-center">
                <div class="col-md-6 order-md-last d-flex">
                    <form action="" class="bg-light p-5 contact-form" method="POST">
                        <a class="navbar-brand center" href="#">Stories<span>.</span></a>
                        {% csrf_token %}
                        {{form.non_field_error}}
                        <div class="form-group">
                            {{form.first_name}}
                            {{form.first_name.errors}}
                        </div>
                        <div class="form-group">
                            {{form.last_name}}
                            {{form.last_name.errors}}
                        </div>
                        <div class="form-group">
                            {{form.username}}
                            {{form.username.errors}}
                        </div>
                        <div class="form-group">
                            {{form.email}}
                            {{form.email.errors}}
                        </div>
                        <div class="form-group">
                            {{form.password1}}
                            {{form.password1.errors}}
                        </div>
                        <div class="form-group">
                            {{form.password2}}
                            {{form.password2.errors}}
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Register" class="btn btn-primary py-3 px-5">
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </section>


<!-- loader -->
<div id="ftco-loader" class="show fullscreen">
    <svg class="circular" width="48px" height="48px">
        <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
        <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                stroke="#F96D00"/>
    </svg>
</div>


    {% endblock content %}


    {% block js %}
    {% endblock %}

food_site/accounts/templates/reset_password.html
{% extends 'base.html' %}
{% load static %}


{% block content %}


<section class="ftco-section contact-section register">
        <div class="container">
            <div class="row block-9 justify-content-center">
                <div class="col-md-6 order-md-last d-flex">
                    <form action="#" class="bg-light p-5 contact-form">
                        <div class="form-group">
                            <h4 class="reset center">Reset your password</h4>
                            <h6 class="center">Please choose a new password to finish signing in.</h6>
                        </div>
                        <div class="form-group">
                            <input type="email" class="form-control" placeholder="New password">
                        </div>
                        <div class="form-group">
                            <input type="email" class="form-control" placeholder="Re-enter new password">
                        </div>
                        <div class="form-group center">
                            <input type="submit" value="Reset password" class="btn btn-primary py-3 px-5">
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </section>


<!-- loader -->
<div id="ftco-loader" class="show fullscreen">
    <svg class="circular" width="48px" height="48px">
        <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
        <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                stroke="#F96D00"/>
    </svg>
</div>


{% endblock content %}


    {% block js %}
    {% endblock %}

food_site/accounts/templates/user-profile.html
{% extends 'base.html' %}
{% load static %}

    {% block content %}



    <section class="ftco-section ftco-no-pt ">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="user-profile-side-bar sidebar-wrap">
                        <div class="sidebar-box p-4 about text-center ftco-animate">
                            <h2 class="heading mb-4">About Me</h2>
                            <img src='{% static "site/images/author.jpg" %}' class="img-fluid" alt="Colorlib Template">
                            <div class="text pt-4">
                                <p>Hi! My name is <strong>Cathy Deon</strong>, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics,
                                    a large language ocean.</p>
                            </div>
                        </div>
                        <div class="sidebar-box ftco-animate user-profile">

                            <a href="single.html" class="btn btn-hover-color py-2">Edit Profile</a>

                        </div>
                        <div class="sidebar-box ftco-animate user-profile">
                            <a href="single.html" class="btn btn-hover-color py-2">Create recipe </a>
                        </div>

                    </div>
                </div>
                <div class="col-lg-9">
                    <div class="row">
                        <div class="col-md-12 heading-section ftco-animate">
                            <h2 class="mb-4"><span>My recipes</span></h2>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4 ftco-animate">
                            <div class="blog-entry">
                                <a class="img-2">

                                    <div class="user-events__edit">
                                        <button type="button" class="edit-event"><i class="fa fa-pencil" aria-hidden="true"></i></button>
                                        <button type="button" class="delete-event"><i class="fa fa-trash" aria-hidden="true"></i></button>
                                    </div>

                                    <img src='{% static "site/images/blog-1.jpg" %}' class="img-fluid" alt="Colorlib Template">
                                </a>
                                <div class="text pt-3">
                                    <p class="meta d-flex"><span class="pr-3">Dessert</span><span class="ml-auto pl-3">March 01, 2018</span>
                                    </p>
                                    <h3><a href="#">Tasty &amp; Delicious Foods</a></h3>
                                    <p class="mb-0"><a href="single.html" class="btn btn-black py-2">Read More <span
                                        class="icon-arrow_forward ml-4"></span></a></p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4 ftco-animate">
                            <div class="blog-entry">
                                <a class="img-2">
                                    <div class="user-events__edit">
                                        <button type="button" class="edit-event"><i class="fa fa-pencil" aria-hidden="true"></i></button>
                                        <button type="button" class="delete-event"><i class="fa fa-trash" aria-hidden="true"></i></button>
                                    </div>
                                    <img src='{% static "site/images/blog-2.jpg" %}' class="img-fluid" alt="Colorlib Template"></a>
                                <div class="text pt-3">
                                    <p class="meta d-flex"><span class="pr-3">Dessert</span><span class="ml-auto pl-3">March 01, 2018</span>
                                    </p>
                                    <h3><a href="#">Tasty &amp; Delicious Foods</a></h3>
                                    <p class="mb-0"><a href="single.html" class="btn btn-black py-2">Read More <span
                                        class="icon-arrow_forward ml-4"></span></a></p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4 ftco-animate">
                            <div class="blog-entry">
                                <a class="img-2">
                                    <div class="user-events__edit">
                                        <button type="button" class="edit-event"><i class="fa fa-pencil" aria-hidden="true"></i></button>
                                        <button type="button" class="delete-event"><i class="fa fa-trash" aria-hidden="true"></i></button>
                                    </div>
                                    <img src='{% static "site/images/blog-3.jpg" %}' class="img-fluid" alt="Colorlib Template"></a>
                                <div class="text pt-3">
                                    <p class="meta d-flex"><span class="pr-3">Dessert</span><span class="ml-auto pl-3">March 01, 2018</span>
                                    </p>
                                    <h3><a href="#">Tasty &amp; Delicious Foods</a></h3>
                                    <p class="mb-0"><a href="single.html" class="btn btn-black py-2">Read More <span
                                        class="icon-arrow_forward ml-4"></span></a></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>


            </div>
        </div>
    </section>



    <!-- loader -->
    <div id="ftco-loader" class="show fullscreen">
        <svg class="circular" width="48px" height="48px">
        <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
        <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                stroke="#F96D00"/>
    </svg>
    </div>


    {% endblock content %}


    {% block js %}
    {% endblock %}