food_site/accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import RegisterView, LoginView, ResetPasswordView, ResetPasswordConfirmView, ProfileView
from django.contrib.auth.views import LogoutView

app_name = 'accounts'
urlpatterns = [
    path('register/', RegisterView.as_view(),name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('log-out/', LogoutView.as_view(), name='log-out'),
    path('reset-password/', ResetPasswordView.as_view(), name='reset-password'),
    path('password-reset-confirm/<str:uidb64>/<str:token>/', ResetPasswordConfirmView.as_view(), name = 'password-reset-confirm'),
    path('user-profile/<int:pk>', ProfileView.as_view(), name='user-profile'),
]

food_site/food_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('stories.urls', namespace='stories')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('api/v1/', include('stories.api.urls', namespace='stories-api')),
]

food_site/stories/api/urls.py
from django.urls import path
from .views import SubscribeAPI

app_name = 'stories-api'

urlpatterns = [
    path('subscribe/', SubscribeAPI.as_view(), name='subscribe'),
]

food_site/stories/urls.py
from django.urls import path

from .views import RecipeListView, ContactView, AboutView, CreateStoryView, IndexView

app_name = "stories"

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('recipes/', RecipeListView.as_view(), name='recipe'),
    path('contacts/', ContactView.as_view(), name='contact'),
    path('create-story/', CreateStoryView.as_view(), name='create_story'),
    path('about/', AboutView.as_view(), name='about'),
    

]

food_site/stories/models.py
from django.db import models
# from django.contrib import get_user_info




class Recipe(models.Model):

    title = models.CharField(max_length=100)
    short_dscrp = models.CharField(max_length=250)
    description = models.TextField(max_length=1000)
    # choice = models.CharField(max_length=50,choices=STATUS_CHOICES,default='male')
    image = models.ImageField(upload_to='images')
    category = models.ForeignKey('Category',on_delete=models.CASCADE,db_index=True,related_name='recipe')
    added_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.title}"


    class Meta:
        verbose_name = "Recipe"
        verbose_name_plural = "Recipes"


class Category(models.Model):
    tag = models.CharField(max_length=150)
    added_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.tag}"

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"



class Comments(models.Model):
    recipes = models.ForeignKey('Recipe', on_delete=models.CASCADE, db_index=True, related_name='comments')
    # author = models.ForeignKey(User, on_delete=models.CASCADE, db_index=True, related_name='comments')
    description = models.TextField(max_length=1000)
    added_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.description}"

    class Meta:
        verbose_name = "Comment"
        verbose_name_plural = "Comments"



class Contact(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=250)
    subject = models.CharField(max_length=250)
    message = models.TextField(max_length=1000)

    added_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        verbose_name = "Contact"
        verbose_name_plural = "Contacts"



class Subscribe(models.Model):
    email = models.EmailField(max_length=250, unique=True)

    added_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        verbose_name = "Subscribe"
        verbose_name_plural = "Subscribes"

    def __str__(self):
        return f"{self.email}"

food_site/stories/forms.py
from .models import Contact, Recipe
from django import forms 

class ContactForm(forms.ModelForm):

    class Meta:
        model = Contact
        fields = ('name', 'email', 'subject', 'message')

        widgets = {
            'name': forms.TextInput(attrs={'id':'firstname','placeholder':'enter name', 'class': 'form-control'}),
            'email': forms.TextInput(attrs={'id':'email','placeholder':'enter email', 'class': 'form-control'}),
            'subject': forms.TextInput(attrs={'id':'subject','placeholder':'enter subject', 'class': 'form-control'}),
            'message': forms.Textarea(attrs={'id':'message','placeholder':'enter message', 'class': 'form-control'}),
        }



class CreateStoryForm(forms.ModelForm):

    class Meta:
        model = Recipe
        fields = ('title', 'short_dscrp','description','image', 'category')


        widgets = {
            'title' : forms.TextInput(attrs={'id': 'title', 'placehoder': 'Enter title', 'class':'form-control'}),
            'short_dscrp' : forms.TextInput(attrs={'id': 'short_dscrp', 'placehoder': 'Short description', 'class':'form-control'}),
            'description' : forms.TextInput(attrs={'id': 'description', 'placehoder': 'Enter description', 'class':'form-control'}),
            'image': forms.FileInput(attrs={'id': 'image', 'placeholder': 'Image', 'class': 'form-control'}),
            'category': forms.Select(attrs={'id': 'category', 'placeholder': 'Category', 'class': 'form-control'}),
        }

food_site/stories/api/views.py
from rest_framework.generics import CreateAPIView
from rest_framework.viewsets import ModelViewSet
from .serializers import SubscribeSerializer
from stories.models import Subscribe

class SubscribeAPI(CreateAPIView):
    queryset = Subscribe.objects.all()
    serializer_class = SubscribeSerializer

food_site/stories/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.urls import reverse_lazy
from stories.models import Recipe, Category
from django.views.generic import ListView, CreateView, DetailView, TemplateView
from .forms import ContactForm, CreateStoryForm

# def recipe(request):
#     recipes = Recipe.objects.all()
#     context = {"recipes": recipes}
#     return render(request,'templates/recipes.html',context)


class RecipeListView(ListView):

    model = Recipe
    context_object_name = "recipes"
    queryset=Recipe.objects.all()
    template_name = 'recipes.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = "asdasdasd"
        return context


class ContactView(CreateView):
    form_class = ContactForm
    template_name = 'contact.html'
    success_url = reverse_lazy('stories:contact')


class CreateStoryView(CreateView):
    form_class = CreateStoryForm
    template_name = 'create_story.html'
    success_url = reverse_lazy('stories:recipe')

class AboutView(TemplateView):
    template_name = 'about.html'

class IndexView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context

food_site/stories/templates/about.html
{% extends 'base.html' %}
{% load static %}


    {% block content %}


<section class="hero-wrap hero-wrap-2" style="background-image: url({% static 'site/images/bg_4.jpg' %});">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text align-items-end justify-content-center">
            <div class="col-md-9 ftco-animate pb-5 text-center">
                <h1 class="mb-3 bread">About Us</h1>
                <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home <i
                        class="ion-ios-arrow-forward"></i></a></span> <span>About us<i
                        class="ion-ios-arrow-forward"></i></span></p>
            </div>
        </div>
    </div>
</section>

<section class="ftco-counter ftco-section ftco-no-pt ftco-no-pb img" id="section-counter">
    <div class="container">
        <div class="row d-flex">
            <div class="col-md-6 d-flex">
                <div class="img d-flex align-self-stretch" style="background-image:url({% static 'site/images/about.jpg' %});"></div>
            </div>
            <div class="col-md-6 pl-md-5 py-5">
                <div class="row justify-content-start pb-3">
                    <div class="col-md-12 heading-section ftco-animate">
                        <h2 class="mb-4"><span>About Stories</span></h2>
                        <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 justify-content-center counter-wrap ftco-animate">
                        <div class="block-18 text-center py-5 bg-light mb-4">
                            <div class="text">
                                <strong class="number" data-number="100">0</strong>
                                <span>Daily visitors</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 justify-content-center counter-wrap ftco-animate">
                        <div class="block-18 text-center py-5 bg-light mb-4">
                            <div class="text">
                                <strong class="number" data-number="200">0</strong>
                                <span>Stories</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 justify-content-center counter-wrap ftco-animate">
                        <div class="block-18 text-center py-5 bg-light mb-4">
                            <div class="text">
                                <strong class="number" data-number="300">0</strong>
                                <span>Recipes</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 justify-content-center counter-wrap ftco-animate">
                        <div class="block-18 text-center py-5 bg-light mb-4">
                            <div class="text">
                                <strong class="number" data-number="40">0</strong>
                                <span>Users</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>



<!-- loader -->
<div id="ftco-loader" class="show fullscreen">
    <svg class="circular" width="48px" height="48px">
        <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
        <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                stroke="#F96D00"/>
    </svg>
</div>


{% endblock content %}


{% block js %}
{% endblock %}

food_site/stories/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
   
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    <title>Document</title>
    {% endblock title %}

    <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,400i,700,700i,900,900i" rel="stylesheet">

    <link rel="stylesheet" href='{% static "site/css/open-iconic-bootstrap.min.css" %}'>
    <link rel="stylesheet" href='{% static "site/css/animate.css" %}'>
    <link rel="stylesheet" href='{% static "site/css/owl.carousel.min.css"%}'>
    <link rel="stylesheet" href='{% static "site/css/owl.theme.default.min.css"%}'>
    <link rel="stylesheet" href='{% static "site/css/magnific-popup.css"%}'>

    <link rel="stylesheet" href='{% static "site/css/aos.css"%}'>

    <link rel="stylesheet" href='{% static "site/css/ionicons.min.css"%}'>

    <link rel="stylesheet" href='{% static "site/css/flaticon.css"%}'>
    <link rel="stylesheet" href='{% static "site/css/icomoon.css"%}'>
    <link rel="stylesheet" href='{% static "site/css/style.css"%}'>
    {% block css %}
    
    {% endblock css %}
</head>
<body>
    {% block header %}
        {% include "header.html" %}
    {% endblock header %}

    {% block content %}

    {% endblock content %}

    {% block subscribe %}
        {% include "subscribe.html" %}
    {% endblock subscribe %}

    {% block footer %}
        {% include "footer.html" %}
    {% endblock footer %}


    <script src='{% static "site/js/jquery.min.js" %}'></script>
    <script src='{% static "site/js/jquery-migrate-3.0.1.min.js" %}'></script>
    <script src='{% static "site/js/popper.min.js" %}'></script>
    <script src='{% static "site/js/bootstrap.min.js" %}'></script>
    <script src='{% static "site/js/jquery.easing.1.3.js" %}'></script>
    <script src='{% static "site/js/jquery.waypoints.min.js" %}'></script>
    <script src='{% static "site/js/jquery.stellar.min.js" %}'></script>
    <script src='{% static "site/js/owl.carousel.min.js" %}'></script>
    <script src='{% static "site/js/jquery.magnific-popup.min.js" %}'></script>
    <script src='{% static "site/js/aos.js" %}'></script>
    <script src='{% static "site/js/jquery.animateNumber.min.js" %}'></script>
    <script src='{% static "site/js/scrollax.min.js" %}'></script>
    <script src='{% static "site/js/google-map.js" %}'></script>
    <script src='{% static "site/js/main.js" %}'></script>
    <script src='{% static "site/js/subscribe.js" %}'></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
    {% block js %}
    {% endblock %}
</body>
</html>

food_site/stories/templates/contact.html
{% extends 'base.html' %}
{% load static %}


    {% block content %}


    <section class="hero-wrap hero-wrap-2" style="background-image: url({% static 'site/images/bg_4.jpg' %});">
        <div class="overlay"></div>
        <div class="container">
            <div class="row no-gutters slider-text align-items-end justify-content-center">
                <div class="col-md-9 ftco-animate pb-5 text-center">
                    <h1 class="mb-3 bread">Contact Us</h1>
                    <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home <i
                        class="ion-ios-arrow-forward"></i></a></span> <span>Contact us<i
                        class="ion-ios-arrow-forward"></i></span></p>
                </div>
            </div>
        </div>
    </section>

    <section class="ftco-section ftco-no-pb contact-section">
        <div class="container">
            <div class="row block-9">
                <div class="col-md-6 order-md-last d-flex">
                    <form action="" class="bg-light p-5 contact-form" method="POST">
                        {% csrf_token %}
                        {{ form.non_field_errors }}
                        <div class="form-group">
                            <label>Name</label>
                            {{ form.name }}
                            {{ form.name.errors }}
                        </div>
                        <div class="form-group">
                            <label>Email</label>
                            {{ form.email }}
                            {{ form.email.errors }}
                        </div>
                        <div class="form-group">
                            <label>Subject</label>
                            {{ form.subject }}
                            {{ form.subject.errors }}
                        </div>
                        <div class="form-group">
                            <label>Message</label>
                            {{ form.message }}
                            {{ form.message.errors }}
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Send Message" class="btn btn-primary py-3 px-5">
                        </div>
                    </form>

                </div>

                <div class="col-md-6 d-flex">
                    <!-- <div id="map" class="bg-white"></div> -->
                    <div class="mapouter"><div class="gmap_canvas"><iframe width="600" height="500" id="gmap_canvas" src="https://maps.google.com/maps?q=university%20of%20san%20francisco&t=&z=13&ie=UTF8&iwloc=&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe><a href="https://www.whatismyip-address.com/nordvpn-coupon/"></a></div><style>.mapouter{position:relative;text-align:right;height:500px;width:600px;}.gmap_canvas {overflow:hidden;background:none!important;height:500px;width:600px;}</style></div>
                </div>
            </div>
        </div>
    </section>

    <section class="ftco-section contact-section">
        <div class="container">
            <div class="row d-flex contact-info">
                <div class="col-md-3 d-flex">
                    <div class="align-self-stretch box p-4 text-center">
                        <div class="icon d-flex align-items-center justify-content-center">
                            <span class="icon-map-signs"></span>
                        </div>
                        <h3 class="mb-4">Address</h3>
                        <p>198 West 21th Street, Suite 721 New York NY 10016</p>
                    </div>
                </div>
                <div class="col-md-3 d-flex">
                    <div class="align-self-stretch box p-4 text-center">
                        <div class="icon d-flex align-items-center justify-content-center">
                            <span class="icon-phone2"></span>
                        </div>
                        <h3 class="mb-4">Contact Number</h3>
                        <p><a href="tel://1234567920">+ 1235 2355 98</a></p>
                    </div>
                </div>
                <div class="col-md-3 d-flex">
                    <div class="align-self-stretch box p-4 text-center">
                        <div class="icon d-flex align-items-center justify-content-center">
                            <span class="icon-paper-plane"></span>
                        </div>
                        <h3 class="mb-4">Email Address</h3>
                        <p><a href="mailto:info@yoursite.com">info@yoursite.com</a></p>
                    </div>
                </div>
                <div class="col-md-3 d-flex">
                    <div class="align-self-stretch box p-4 text-center">
                        <div class="icon d-flex align-items-center justify-content-center">
                            <span class="icon-globe"></span>
                        </div>
                        <h3 class="mb-4">Website</h3>
                        <p><a href="#">yoursite.com</a></p>
                    </div>
                </div>
            </div>
        </div>
    </section>



    <!-- loader -->
    <div id="ftco-loader" class="show fullscreen">
        <svg class="circular" width="48px" height="48px">
        <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
        <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                stroke="#F96D00"/>
    </svg>
    </div>


    {% endblock content %}


    {% block js %}
    {% endblock %}

food_site/stories/templates/create_story.html
{% extends 'base.html' %}
{% load static %}


    {% block content %}

    <section class="ftco-section contact-section create-story">
        <div class="container">
            <div class="row block-9 justify-content-center">
                <div class="col-md-6 order-md-last d-flex">
                    <form action="" class="bg-light p-5 contact-form" method="POST" enctype="multipart/form-data">
                        <a class="navbar-brand center" href="#">Stories<span>.</span></a>
                        {% csrf_token %}
                        {{form.non_field_error}}
                        <div class="form-group">
                            {{form.title}}
                            {{form.title.errors}}
                        </div>
                        <div class="form-group">
                            {{form.short_dscrp}}
                            {{form.short_dscrp.errors}}
                        </div>
                        <div class="form-group">
                            {{form.description}}
                            {{form.description.errors}}
                        </div>
                        <div class="form-group">
                            {{form.category}}
                            {{form.category.errors}}
                        </div>
                        <!-- <div class="form-group">
                            {{form.tag}}
                            {{form.tag.errors}}
                        </div> -->
                        <div class="form-group">
                            {{form.image}}
                            {{form.image.errors}}
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Create" class="btn btn-primary py-3 px-5">
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </section>
    

    <!-- loader -->
    <div id="ftco-loader" class="show fullscreen">
        <svg class="circular" width="48px" height="48px">
            <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" />
            <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                stroke="#F96D00" />
        </svg>
    </div>


    {% endblock content %}


    {% block js %}
    {% endblock %}

food_site/stories/templates/footer.html
<footer class="ftco-footer ftco-footer-2 ftco-section">
    <div class="container">
        <div class="row mb-5">
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Stories</h2>
                    <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
                    <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                        <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4 ml-md-5">
                    <h2 class="ftco-heading-2">Information</h2>
                    <ul class="list-unstyled">
                        <li><a href="#" class="py-2 d-block">Terms of Uses</a></li>
                        <li><a href="#" class="py-2 d-block">About Stories</a></li>
                        <li><a href="#" class="py-2 d-block">Privacy Policy</a></li>
                        <li><a href="#" class="py-2 d-block">Accessibility Help</a></li>
                        <li><a href="#" class="py-2 d-block">Advertise with us</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Categories</h2>
                    <ul class="list-unstyled">
                        <li><a href="#" class="py-2 d-block">Food</a></li>
                        <li><a href="#" class="py-2 d-block">Restaurant</a></li>
                        <li><a href="#" class="py-2 d-block">Dessert</a></li>
                        <li><a href="#" class="py-2 d-block">Lifestyle</a></li>
                        <li><a href="#" class="py-2 d-block">Recipes</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Have a Questions?</h2>
                    <div class="block-23 mb-3">
                        <ul>
                            <li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span>
                            </li>
                            <li><a href="#"><span class="icon icon-phone"></span><span
                                class="text">+2 392 3929 210</span></a></li>
                            <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@yourdomain.com</span></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 text-center">

                <p>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;
                    <script>
                        document.write(new Date().getFullYear());
                    </script>
                    All rights reserved | This template is made with <i class="icon-heart color-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </p>
            </div>
        </div>
    </div>
</footer>

food_site/stories/templates/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark ftco-navbar-light" id="ftco-navbar">
    <div class="container">
        <a class="navbar-brand" href="index.html">Stories<span>.</span></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="oi oi-menu"></span> Menu
    </button>

        <div class="collapse navbar-collapse" id="ftco-nav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active"><a href="{% url 'stories:index' %}" class="nav-link">Home</a></li>
                    <li class="nav-item"><a href="{% url 'stories:about' %}" class="nav-link">About</a></li>
                    <li class="nav-item"><a href="{% url 'stories:create_story' %}" class="nav-link">Stories</a></li>
                    <li class="nav-item"><a href="{% url 'stories:recipe' %}" class="nav-link">Recipes</a></li>
                    <li class="nav-item"><a href="{% url 'stories:contact' %}" class="nav-link">Contact</a></li>
                    {% if request.user.is_authenticated %}
                            daxil olunub
                    {% else %}
                    daxil olunmayib
                    {% endif %}
                    
                <li><a href="{% url 'accounts:login' %}" class="btn btn-black px-3 px-md-4 py-3">Sign in</a></li>
            </ul>
        </div>
    </div>
</nav>

food_site/stories/templates/subscribe.html
<section class="ftco-subscribe ftco-section bg-light">
    <div class="overlay">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-md-8 text-wrap text-center heading-section ftco-animate">
                    <h2 class="mb-4"><span>Subcribe to our Newsletter</span></h2>
                    <p>A small river named Duden flows by their place and supplies it with the necessary regelialia. It
                        is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
                    <div class="row d-flex justify-content-center mt-4 mb-4">
                        <div class="col-md-8">
                            <form action="" method='post' class="subscribe-form">
                                {% csrf_token %}
                                <div class="form-group d-flex">
                                    <input type="email" name="email" id="email">
                                    <input type="submit" value="Subscribe" class="submit px-3">
                                </div>
                            </form>
                        </div>
                    </div>
                    <div id="message">
                        <p></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>